server:
  port: 8080
spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/portafolio
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres